### ISSUE TITLE
use of synchronize for moving directory?

### ISSUE THREAD

**Issue by tryge** [fubarhouse/ansible-role-jetbrains-hub#1]
I'm trying to use the role you provided on `macOS` provisioning a virtual machine running `ubuntu 14.04`. So far I've run into following issues:

1) needed to set `foobarhous_user = root`, which is not mentioned in the readme, otherwise there's an error
2) as far as I understand, when moving the installation directory (task 'Hub | Moving to installation directory') with synchronize it tries to copy from my host machine to the target machine instead of just copying within the target machine. Of course the files don't exist on my host machine, therefore it fails.

```
fatal: [hub]: FAILED! => {"changed": false, "cmd": "/usr/bin/rsync --delay-updates -F --compress --delete-after --archive --rsh 'ssh -i /XXX/private_key -S none -o StrictHostKeyChecking=no -o Port=2200' --rsync-path=\"sudo rsync\" --out-format='<<CHANGED>>%i %n%L' \"/tmp/hub-ring-bundle-2.5.450/\" \"vagrant@127.0.0.1:/usr/local/hub\"", "failed": true, "msg": "Warning: Permanently added '[127.0.0.1]:2200' (ECDSA) to the list of known hosts.\r\nrsync: link_stat \"/tmp/hub-ring-bundle-2.5.450/.\" failed: No such file or directory (2)\nrsync error: some files could not be transferred (code 23) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-47/rsync/main.c(992) [sender=2.6.9]\n", "rc": 23}
```

Disclaimer: I'm very new to ansible and might not understand what's actually going on.

**Comment by fubarhouse** [comment]
I'll check it out, but in the first instance there's a typo here.
`foobarhous_user` needs to be `fubarhouse_user`

`fubarhouse_user` is established in the dependency role `fubarhouse.commons` though there is something there recently that I've noticed I need to look at.

FYI, the synchronize is basically an implementation of the rsync command, and I've set it up to affect the guest to guest. My assumption is that you're running ansible via the vagrant provision command (provisioning guest from host).

For the time being, could you please try to run it on the vm directly? I'll open a range of tickets to identify and fix this problem - I get a feeling I know what it is and it'll affect quite a lot of my roles.

If you need help doing this, please let me know.

**Comment by fubarhouse** [comment]
Please note I've got a fix in place ready to commit. - It's not the most elegant solution but I can always revisit it.
I thank you for noticing this, I'll begin rolling out fixes soon.

**Comment by fubarhouse** [comment]
This one is now released, let me know if you continue to have problems.
Make sure you update the role before rerunning it!

```
ansible-galaxy install fubarhouse.commons -f;
ansible-galaxy install fubarhouse.commons -f;
````

Now closing, but feel free to reopen it.
