### ISSUE TITLE
Hub fails to startup

### ISSUE THREAD

**Issue by tryge** [fubarhouse/ansible-role-jetbrains-hub#2]
Thank you for fixing the previous error, I still need to define the user for downloading, but the installation worked.

However, when Hub is started the first time, it is started as root user leading to some directories and files ending up with `root:root` owner.

I guess the error is in the task `Hub | Service | Configure port` where you'd need to become `hub` user and not `root`.

**Comment by fubarhouse** [comment]
-edited-

Having a better look, it seems all of that stuff is happening within the shell script as you've pointed out - I'm getting tests to pass when executing that task as user `vagrant`. Would changing the user of this task satisfy your requirements/expectations?

I have no argument against this change it as the tests I've run are passing.

**Comment by tryge** [comment]
I'd execute the task as user `hub` as this is the user that will also be used by the service that is being setup, but if `vagrant` works then it is fine for me.

EDIT: also the error is not seen in ansible as hub starts, but immediately stops again.
EDIT^2: I mean the original error, just to avoid confusion :-)

**Comment by fubarhouse** [comment]
User `hub` is created during this process, so consider it done.

**Comment by fubarhouse** [comment]
There will be a delay, apparently the `hub` user is a non-privileged user so I need to find a way around this before I can make any changes to this repository.

**Comment by fubarhouse** [comment]
Commit is now being tested by Travis, Ansible provides a way around unprivileged access to temporary files via ssh. I'll do some additional testing without ssh and release it tonight.

**Comment by tryge** [comment]
Great, thank you!

**Comment by fubarhouse** [comment]
`hub_user` and `hub_mode` are now configurable, and the script will now execute as `hub_user`.

Closing, feel free to reopen. Make sure you update properly via Ansible Galaxy.

I'm not sure as to the correct mode for the file system, but you now have the option of changing it via the `hub_mode` variable, which defaults to 0777.

**Comment by tryge** [comment]
Thank you! Installation works fine now.
